# Generated by Django 3.1.7 on 2021-03-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_author',
            new_name='user',
        ),
    ]
