# Generated by Django 3.1.7 on 2021-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210304_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_rate',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='article_news_rate',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='chapter',
            field=models.CharField(max_length=200),
        ),
    ]
