# Generated by Django 3.1.7 on 2021-03-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210307_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_news_article',
            field=models.CharField(choices=[('NE', 'Новость'), ('AR', 'Статья')], default='news', max_length=2),
        ),
    ]
