# Generated by Django 3.1.7 on 2021-03-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210307_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user_name',
        ),
    ]
