# Generated by Django 3.1.7 on 2021-04-22 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='author',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
    ]
